### ISSUE TITLE
Data on site is missing for November 2022, January 2023

### ISSUE THREAD

**Issue by handelaar** [HowTheyVote/howtheyvote#844]
That's the whole bug report.  Several days of stuff missing :)

**Comment by linusha** [comment]
Hi @handelaar, thanks for reporting this! :slightly_smiling_face: 
We are aware of this issue, but had not yet time to investigate what the underlying cause is. I will ping you here, when we had some time to find out and have the data available.

**Until then - please be aware, that this is not the only issue with the current state of our data. Even for days where we show votes, we seldomly have all the votes but there are missings.**

**Comment by tillprochaska** [comment]
It took some time to get there, but we have recently launched an overhauled version of HowTheyVote.eu. We have significantly improved completeness and quality of the data available.
